### ISSUE TITLE
Add CONTRIBUTION.md file to specify guidelines to contribute

### ISSUE THREAD

**Issue by FlutterNinjas** [FlutterNinjas/uber-clone#3]
To claim this issue first add a comment

**Comment by nidhi-o20** [comment]
I would like to prepare this document

**Comment by nidhi-o20** [comment]
can you provide basic guidelines which you would like to follow

**Comment by FlutterNinjas** [comment]
You can refer this link
https://opensource.com/life/16/3/contributor-guidelines-template-and-tips
